namespace Codevoid.MusicHall
{
    [default_interface]
    runtimeclass MainUI : Windows.UI.Xaml.Controls.UserControl
    {
        MainUI();
        void Navigate(Windows.UI.Xaml.Interop.TypeName pageType, IInspectable parameter);
    }
}
